Limpieza y manipulacion de datos

In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_spss(
    '../Data/201703_EnemduBDD_viviendahogar.sav'
)

In [4]:
df.columns

Index(['area', 'ciudad', 'zona', 'sector', 'panelm', 'vivienda', 'hogar',
       'vi01', 'vi02', 'vi03a', 'vi03b', 'vi04a', 'vi04b', 'vi05a', 'vi05b',
       'vi06', 'vi07', 'vi07a', 'vi08', 'vi09', 'vi10', 'vi10a', 'vi11',
       'vi12', 'vi13', 'vi14', 'plan_muestreo', 'fexp'],
      dtype='object')

In [5]:
df.dtypes

area             category
ciudad            float64
zona               object
sector             object
panelm           category
vivienda         category
hogar            category
vi01             category
vi02             category
vi03a            category
vi03b            category
vi04a            category
vi04b            category
vi05a            category
vi05b            category
vi06             category
vi07             category
vi07a            category
vi08             category
vi09             category
vi10             category
vi10a            category
vi11             category
vi12             category
vi13             category
vi14             category
plan_muestreo      object
fexp              float64
dtype: object

In [6]:
ser = df.isnull().sum(axis=1)

In [7]:
(ser > 0).sum()

15107

In [8]:
ser

0        1
1        1
2        1
3        1
4        1
        ..
15824    1
15825    1
15826    1
15827    1
15828    1
Length: 15829, dtype: int64

In [9]:
df.isnull().any(axis=1)

0        True
1        True
2        True
3        True
4        True
         ...
15824    True
15825    True
15826    True
15827    True
15828    True
Length: 15829, dtype: bool

In [10]:
df.isnull().any(axis=1).sum()

15107

In [11]:
df.isnull().all(axis=1)

0        False
1        False
2        False
3        False
4        False
         ...
15824    False
15825    False
15826    False
15827    False
15828    False
Length: 15829, dtype: bool

In [12]:
df.isnull().all(axis=1).sum()

0

In [13]:
df['area'].isnull()

0        False
1        False
2        False
3        False
4        False
         ...
15824    False
15825    False
15826    False
15827    False
15828    False
Name: area, Length: 15829, dtype: bool

In [14]:
df['area'].isnull().sum()

0

In [15]:
df['ciudad'].isna()

0        False
1        False
2        False
3        False
4        False
         ...
15824    False
15825    False
15826    False
15827    False
15828    False
Name: ciudad, Length: 15829, dtype: bool

In [16]:
df['ciudad'].notnull().sum()

15829

In [17]:
df.index

RangeIndex(start=0, stop=15829, step=1)

In [18]:
df.iloc[:5, :3]

     area   ciudad zona
0  Urbana  10150.0  001
1  Urbana  10150.0  001
2  Urbana  10150.0  001
3  Urbana  10150.0  001
4  Urbana  10150.0  001

In [19]:
df.iloc[:, -3:]

                             vi14 plan_muestreo        fexp
0      Propia y totalmente pagada          1013   78.141584
1                     En arriendo          1013   78.141584
2        Propia y la está pagando          1013   78.141584
3      Propia y totalmente pagada          1013   78.141584
4                     En arriendo          1013   78.141584
...                           ...           ...         ...
15824  Propia y totalmente pagada           290  177.514885
15825  Propia y totalmente pagada           290  177.514885
15826      Recibida por servicios           290  177.514885
15827  Propia y totalmente pagada           290  177.514885
15828  Propia y totalmente pagada           290  177.514885

[15829 rows x 3 columns]

In [20]:
df.iloc[:,[0, 3, 9]]

         area sector             vi03a
0      Urbana    003              Teja
1      Urbana    003  Asbesto, eternit
2      Urbana    003  Asbesto, eternit
3      Urbana    003              Teja
4      Urbana    003              Teja
...       ...    ...               ...
15824   Rural    007              Zinc
15825   Rural    007              Zinc
15826   Rural    007              Zinc
15827   Rural    007              Zinc
15828   Rural    007              Zinc

[15829 rows x 3 columns]

In [21]:
df_sliced = df.loc[:,['area', 'sector']]

In [22]:
df_sliced.isnull().all(axis=1).sum()

0

In [23]:
df.iloc[3, :]

area                                                Urbana
ciudad                                             10150.0
zona                                                   001
sector                                                 003
panelm                                            Panel L2
vivienda                                      Vivienda Uno
hogar                                            Hogar Uno
vi01             Carretera, calle pavimentada o adoquinada
vi02                                          Casa o villa
vi03a                                                 Teja
vi03b                                              Regular
vi04a                             Tabla, tablón no tratado
vi04b                                                Bueno
vi05a                           Hormigón, bloque, ladrillo
vi05b                                                Bueno
vi06                                                   8.0
vi07                                                   6.0
vi07a                                                  NaN
vi08                                                   Gas
vi09                             Excusado y alcantarillado
vi10                               Otra fuente por tubería
vi10a                    Por tubería dentro de la vivienda
vi11                                   Exclusivo del hogar
vi12                             Empresa eléctrica pública
vi13                                    Servicio municipal
vi14                            Propia y totalmente pagada
plan_muestreo                                         1013
fexp                                             78.141584
Name: 3, dtype: object

In [24]:
df.iloc[3, 5]

'Vivienda Uno'

In [25]:
df.loc[:, 'area']

0        Urbana
1        Urbana
2        Urbana
3        Urbana
4        Urbana
          ...
15824     Rural
15825     Rural
15826     Rural
15827     Rural
15828     Rural
Name: area, Length: 15829, dtype: category
Categories (2, object): ['Rural', 'Urbana']

In [26]:
df.loc[:, 'area' : 'sector']

         area    ciudad zona sector
0      Urbana   10150.0  001    003
1      Urbana   10150.0  001    003
2      Urbana   10150.0  001    003
3      Urbana   10150.0  001    003
4      Urbana   10150.0  001    003
...       ...       ...  ...    ...
15824   Rural  900451.0  999    007
15825   Rural  900451.0  999    007
15826   Rural  900451.0  999    007
15827   Rural  900451.0  999    007
15828   Rural  900451.0  999    007

[15829 rows x 4 columns]

In [27]:
df.loc[:, ['ciudad', 'sector']]

         ciudad sector
0       10150.0    003
1       10150.0    003
2       10150.0    003
3       10150.0    003
4       10150.0    003
...         ...    ...
15824  900451.0    007
15825  900451.0    007
15826  900451.0    007
15827  900451.0    007
15828  900451.0    007

[15829 rows x 2 columns]

In [28]:
new_df = pd.read_csv(
    '../Data/data_2019.csv'
)

In [29]:
new_df

,antigüedad,cuartos,cuartosdebaño,estacionamiento,latlong,metroscuadradostotales,precio,publicado,tipodevendedor,titulo
0,En construcción,3,3,2,//maps.google.com/maps/api/staticmap?center=-2...,319m²,NaN,NaN,NaN,Casa en Venta en Estancias del Rio
1,En construcción,4,4,0,//maps.google.com/maps/api/staticmap?center=-2...,410m²,NaN,NaN,NaN,Isla Mocoli Urb. Pacifica - 4 Dorm.
2,NaN,1,1,3,//maps.google.com/maps/api/staticmap?center=-2...,83m²,NaN,NaN,NaN,Vendo Casa de Estreno Urbanizacion Villa Itali...
3,5,3,4,2,//maps.google.com/maps/api/staticmap?center=-2...,186m²,NaN,NaN,NaN,Hermosa Casa en Venta Urb. Arcadia - 3 Dorm. 2...
4,5,4,4,0,//maps.google.com/maps/api/staticmap?center=-2...,480m²,NaN,NaN,NaN,Arrecife - Punta Mocoli Design By Jannina Cabal
...,...,...,...,...,...,...,...,...,...,...
10277,En construcción,4,4,2,//maps.google.com/maps/api/staticmap?center=nu...,660m²,USD 590.000,NaN,NaN,Proyecto Al Lago en La Peninsula - Mocoli
10278,4,5,6,2,//maps.google.com/maps/api/staticmap?center=nu...,700m²,USD 790.000,NaN,NaN,Venta Villa Preciosa Super Amplia 5 Dorm.
10279,6,3,4,2,//maps.google.com/maps/api/staticmap?center=-2...,350m²,USD 380.000,NaN,NaN,Oportunidad Moderna Casa en Via a La Costa Urb...
10280,1,1,2,2,//maps.google.com/maps/api/staticmap?center=nu...,256m²,USD 220.000,NaN,NaN,Venta C Celeste Villa 1 Sola Planta 1 Dormitor...
10281,14,4,0,1,//maps.google.com/maps/api/staticmap?center=nu...,230m²,USD 285.000,NaN,NaN,Villa X Uess 4 Dormitorio Estudio

In [30]:
new_df.dropna(subset= ['titulo', 'metroscuadradostotales', 'precio', 'latlong'], inplace=True)

In [31]:
new_df

,antigüedad,cuartos,cuartosdebaño,estacionamiento,latlong,metroscuadradostotales,precio,publicado,tipodevendedor,titulo
5130,antigüedad,cuartos,cuartosdebaño,estacionamiento,latlong,metroscuadradostotales,precio,publicado,tipodevendedor,titulo
5131,5,4,4,0,//maps.google.com/maps/api/staticmap?center=-2...,480m²,USD 565.000,NaN,NaN,Arrecife - Punta Mocoli Design By Jannina Cabal
5132,A estrenar,4,3,2,//maps.google.com/maps/api/staticmap?center=-2...,400m²,USD 370.000,NaN,NaN,Vendo Casa Moderna de Estreno en Isla Mocoli
5133,20,4,4,3,//maps.google.com/maps/api/staticmap?center=-2...,244m²,USD 140.000,NaN,NaN,Venta de Casa Cdla. del Biess Remodelada - Sec...
5134,En construcción,0,4,2,//maps.google.com/maps/api/staticmap?center=-2...,1m²,USD 259.000,NaN,NaN,Se Vende Proyecto en Isla Celeste Reserva Solo...
...,...,...,...,...,...,...,...,...,...,...
10277,En construcción,4,4,2,//maps.google.com/maps/api/staticmap?center=nu...,660m²,USD 590.000,NaN,NaN,Proyecto Al Lago en La Peninsula - Mocoli
10278,4,5,6,2,//maps.google.com/maps/api/staticmap?center=nu...,700m²,USD 790.000,NaN,NaN,Venta Villa Preciosa Super Amplia 5 Dorm.
10279,6,3,4,2,//maps.google.com/maps/api/staticmap?center=-2...,350m²,USD 380.000,NaN,NaN,Oportunidad Moderna Casa en Via a La Costa Urb...
10280,1,1,2,2,//maps.google.com/maps/api/staticmap?center=nu...,256m²,USD 220.000,NaN,NaN,Venta C Celeste Villa 1 Sola Planta 1 Dormitor...
10281,14,4,0,1,//maps.google.com/maps/api/staticmap?center=nu...,230m²,USD 285.000,NaN,NaN,Villa X Uess 4 Dormitorio Estudio

In [32]:
new_df.reset_index()

,index,antigüedad,cuartos,cuartosdebaño,estacionamiento,latlong,metroscuadradostotales,precio,publicado,tipodevendedor,titulo
0,5130,antigüedad,cuartos,cuartosdebaño,estacionamiento,latlong,metroscuadradostotales,precio,publicado,tipodevendedor,titulo
1,5131,5,4,4,0,//maps.google.com/maps/api/staticmap?center=-2...,480m²,USD 565.000,NaN,NaN,Arrecife - Punta Mocoli Design By Jannina Cabal
2,5132,A estrenar,4,3,2,//maps.google.com/maps/api/staticmap?center=-2...,400m²,USD 370.000,NaN,NaN,Vendo Casa Moderna de Estreno en Isla Mocoli
3,5133,20,4,4,3,//maps.google.com/maps/api/staticmap?center=-2...,244m²,USD 140.000,NaN,NaN,Venta de Casa Cdla. del Biess Remodelada - Sec...
4,5134,En construcción,0,4,2,//maps.google.com/maps/api/staticmap?center=-2...,1m²,USD 259.000,NaN,NaN,Se Vende Proyecto en Isla Celeste Reserva Solo...
...,...,...,...,...,...,...,...,...,...,...,...
5016,10277,En construcción,4,4,2,//maps.google.com/maps/api/staticmap?center=nu...,660m²,USD 590.000,NaN,NaN,Proyecto Al Lago en La Peninsula - Mocoli
5017,10278,4,5,6,2,//maps.google.com/maps/api/staticmap?center=nu...,700m²,USD 790.000,NaN,NaN,Venta Villa Preciosa Super Amplia 5 Dorm.
5018,10279,6,3,4,2,//maps.google.com/maps/api/staticmap?center=-2...,350m²,USD 380.000,NaN,NaN,Oportunidad Moderna Casa en Via a La Costa Urb...
5019,10280,1,1,2,2,//maps.google.com/maps/api/staticmap?center=nu...,256m²,USD 220.000,NaN,NaN,Venta C Celeste Villa 1 Sola Planta 1 Dormitor...
5020,10281,14,4,0,1,//maps.google.com/maps/api/staticmap?center=nu...,230m²,USD 285.000,NaN,NaN,Villa X Uess 4 Dormitorio Estudio

In [33]:
new_df.reset_index(drop=True)

,antigüedad,cuartos,cuartosdebaño,estacionamiento,latlong,metroscuadradostotales,precio,publicado,tipodevendedor,titulo
0,antigüedad,cuartos,cuartosdebaño,estacionamiento,latlong,metroscuadradostotales,precio,publicado,tipodevendedor,titulo
1,5,4,4,0,//maps.google.com/maps/api/staticmap?center=-2...,480m²,USD 565.000,NaN,NaN,Arrecife - Punta Mocoli Design By Jannina Cabal
2,A estrenar,4,3,2,//maps.google.com/maps/api/staticmap?center=-2...,400m²,USD 370.000,NaN,NaN,Vendo Casa Moderna de Estreno en Isla Mocoli
3,20,4,4,3,//maps.google.com/maps/api/staticmap?center=-2...,244m²,USD 140.000,NaN,NaN,Venta de Casa Cdla. del Biess Remodelada - Sec...
4,En construcción,0,4,2,//maps.google.com/maps/api/staticmap?center=-2...,1m²,USD 259.000,NaN,NaN,Se Vende Proyecto en Isla Celeste Reserva Solo...
...,...,...,...,...,...,...,...,...,...,...
5016,En construcción,4,4,2,//maps.google.com/maps/api/staticmap?center=nu...,660m²,USD 590.000,NaN,NaN,Proyecto Al Lago en La Peninsula - Mocoli
5017,4,5,6,2,//maps.google.com/maps/api/staticmap?center=nu...,700m²,USD 790.000,NaN,NaN,Venta Villa Preciosa Super Amplia 5 Dorm.
5018,6,3,4,2,//maps.google.com/maps/api/staticmap?center=-2...,350m²,USD 380.000,NaN,NaN,Oportunidad Moderna Casa en Via a La Costa Urb...
5019,1,1,2,2,//maps.google.com/maps/api/staticmap?center=nu...,256m²,USD 220.000,NaN,NaN,Venta C Celeste Villa 1 Sola Planta 1 Dormitor...
5020,14,4,0,1,//maps.google.com/maps/api/staticmap?center=nu...,230m²,USD 285.000,NaN,NaN,Villa X Uess 4 Dormitorio Estudio

In [34]:
new_df.reset_index(drop=True, inplace=True)

In [35]:
new_df.head()

,antigüedad,cuartos,cuartosdebaño,estacionamiento,latlong,metroscuadradostotales,precio,publicado,tipodevendedor,titulo
0,antigüedad,cuartos,cuartosdebaño,estacionamiento,latlong,metroscuadradostotales,precio,publicado,tipodevendedor,titulo
1,5,4,4,0,//maps.google.com/maps/api/staticmap?center=-2...,480m²,USD 565.000,NaN,NaN,Arrecife - Punta Mocoli Design By Jannina Cabal
2,A estrenar,4,3,2,//maps.google.com/maps/api/staticmap?center=-2...,400m²,USD 370.000,NaN,NaN,Vendo Casa Moderna de Estreno en Isla Mocoli
3,20,4,4,3,//maps.google.com/maps/api/staticmap?center=-2...,244m²,USD 140.000,NaN,NaN,Venta de Casa Cdla. del Biess Remodelada - Sec...
4,En construcción,0,4,2,//maps.google.com/maps/api/staticmap?center=-2...,1m²,USD 259.000,NaN,NaN,Se Vende Proyecto en Isla Celeste Reserva Solo...

In [36]:
new_df.drop(columns=["antigüedad", "cuartos", "cuartosdebaño", "estacionamiento", "publicado", "tipodevendedor"], inplace=True)

In [37]:
new_df

,latlong,metroscuadradostotales,precio,titulo
0,latlong,metroscuadradostotales,precio,titulo
1,//maps.google.com/maps/api/staticmap?center=-2...,480m²,USD 565.000,Arrecife - Punta Mocoli Design By Jannina Cabal
2,//maps.google.com/maps/api/staticmap?center=-2...,400m²,USD 370.000,Vendo Casa Moderna de Estreno en Isla Mocoli
3,//maps.google.com/maps/api/staticmap?center=-2...,244m²,USD 140.000,Venta de Casa Cdla. del Biess Remodelada - Sec...
4,//maps.google.com/maps/api/staticmap?center=-2...,1m²,USD 259.000,Se Vende Proyecto en Isla Celeste Reserva Solo...
...,...,...,...,...
5016,//maps.google.com/maps/api/staticmap?center=nu...,660m²,USD 590.000,Proyecto Al Lago en La Peninsula - Mocoli
5017,//maps.google.com/maps/api/staticmap?center=nu...,700m²,USD 790.000,Venta Villa Preciosa Super Amplia 5 Dorm.
5018,//maps.google.com/maps/api/staticmap?center=-2...,350m²,USD 380.000,Oportunidad Moderna Casa en Via a La Costa Urb...
5019,//maps.google.com/maps/api/staticmap?center=nu...,256m²,USD 220.000,Venta C Celeste Villa 1 Sola Planta 1 Dormitor...
5020,//maps.google.com/maps/api/staticmap?center=nu...,230m²,USD 285.000,Villa X Uess 4 Dormitorio Estudio

Clase del jueves

In [38]:
new_df['metroscuadradostotales'] != 'metroscuadradostotales'

0       False
1        True
2        True
3        True
4        True
        ...
5016     True
5017     True
5018     True
5019     True
5020     True
Name: metroscuadradostotales, Length: 5021, dtype: bool

In [39]:
new_df['metroscuadradostotales'].unique()

array(['metroscuadradostotales', '480m²', '400m²', '244m²', '1m²',
       '245m²', '1090m²', '580m²', '505m²', '240m²', '170m²', '319m²',
       '593m²', '186m²', '570m²', '189m²', '461m²', '83m²', '405m²',
       '410m²', '600m²', '767m²', '250m²', '180m²', '550m²', '160m²',
       '2000m²', '105m²', '103m²', '120m²', '96m²', '268m²', '230m²',
       '175m²', '104m²', '546m²', '203m²', '200m²', '1460m²', '144m²',
       '540m²', '470m²', '251m²', '740m²', '530m²', '290m²', '122m²',
       '72m²', '90m²', '406m²', '127m²', '337m²', '453m²', '423m²',
       '502m²', '420m²', '101m²', '243m²', '56m²', '456m²', '138m²',
       '523m²', '225m²', '316m²', '1088m²', '263m²', '132m²', '112m²',
       '324m²', '854m²', '113m²', '156m²', '258m²', '147m²', '255m²',
       '297m²', '330m²', '1700m²', '364m²', '450m²', '276m²', '142m²',
       '396m²', '210m²', '500m²', '472m²', '495m²', '238m²', '267m²',
       '214m²', '194m²', '150m²', '82m²', '227m²', '320m²', '315m²',
       '460m²', '135m²', '260m²', '220m²', '93m²', '351m²', '447m²',
       '121m²', '493m²', '153m²', '445m²', '278m²', '300m²', '1000m²',
       '185m²', '435m²', '630m²', '350m²', '161m²', '750m²', '130m²',
       '650m²', '473m²', '365m²', '152m²', '565m²', '257m²', '208m²',
       '192m²', '325m²', '76m²', '367m²', '190m²', '139m²', '390m²',
       '202m²', '412m²', '560m²', '1200m²', '510m²', '938m²', '486m²',
       '183m²', '125m²', '728m²', '123m²', '80m²', '374m²', '100m²',
       '567m²', '950m²', '1300m²', '187m²', '332m²', '217m²', '140m²',
       '700m²', '432m²', '1010m²', '287m²', '1900m²', '710m²', '254m²',
       '275m²', '1400m²', '231m²', '1101m²', '545m²', '1600m²', '407m²',
       '380m²', '98m²', '465m²', '373m²', '77m²', '307m²', '106m²',
       '517m²', '519m²', '1500m²', '233m²', '133m²', '216m²', '397m²',
       '625m²', '835m²', '322m²', '266m²', '703m²', '532m²', '256m²',
       '609m²', '295m²', '109m²', '484m²', '653m²', '857m²', '383m²',
       '680m²', '280m²', '164m²', '2400m²', '234m²', '394m²', '1157m²',
       '114m²', '640m²', '360m²', '675m²', '503m²', '820m²', '136m²',
       '206m²', '960m²', '370m²', '86m²', '366m²', '591m²', '304m²',
       '162m²', '900m²', '85m²', '226m²', '259m²', '247m²', '305m²',
       '584m²', '1048m²', '568m²', '595m²', '404m²', '91m²', '896m²',
       '252m²', '126m²', '478m²', '264m²', '764m²', '356m²', '218m²',
       '930m²', '375m²', '182m²', '149m²', '312m²', '207m²', '344m²',
       '760m²', '154m²', '773m²', '163m²', '1520m²', '1050m²', '800m²',
       '796m²', '498m²', '111m²', '148m²', '204m²', '346m²', '457m²',
       '313m²', '850m²', '78m²', '825m²', '1100m²', '355m²', '1230m²',
       '134m²', '638m²', '860m²', '108m²', '1217m²', '303m²', '165m²',
       '1575m²', '1550m²', '131m²', '477m²', '393m²', '671m²', '454m²',
       '790m²', '2286m²', '476m²', '224m²', '855m²', '514m²', '262m²',
       '1270m²', '188m²', '110m²', '213m²', '155m²', '1305m²', '467m²',
       '1350m²', '288m²', '770m²', '169m²', '1232m²', '176m²', '1310m²',
       '141m²', '246m²', '848m²', '980m²', '102m²', '347m²', '521m²',
       '805m²', '362m²', '205m²', '426m²', '167m²', '1720m²', '191m²',
       '124m²', '195m²', '515m²', '520m²', '253m²', '6000m²', '1746m²',
       '670m²', '129m²', '1007m²', '117m²', '387m²', '237m²', '615m²',
       '489m²', '340m²', '181m²', '466m²', '335m²', '488m²', '221m²',
       '542m²', '439m²', '328m²', '996m²', '2345m²', '95m²', '525m²',
       '1098m²', '84m²', '173m²', '1055m²', '660m²', '317m²', '648m²',
       '1722m²', '177m²', '60m²', '658m²', '2720m²', '235m²', '581m²',
       '94m²', '880m²', '212m²', '487m²', '232m²', '598m²', '378m²',
       '574m²', '87m²', '693m²', '1249m²', '620m²', '444m²', '281m²',
       '935m²', '1175m²', '384m²', '612m²', '292m²', '45772m²', '721m²',
       '92m²', '1210m²', '644m²', '166m²', '81m²', '239m²', '722m²',
       '352m²', '172m²', '392m²', '395m²', '528m²', '429m²', '1049m²',
       '285m²', '549m²', '890m²', '159m²', '67m²', '534m²', '1181m²',
       '957m²', '657m²', '1002m²', '145m²', '270m²', '512m²', '184m²',
       '196m²', '832m²', '1800m²', '1640m²', '197m²', '865m²', '2095m²',
       '219m²', '590m²', '702m²', '398m²', '2600m²', '249m²', '229m²',
       '338m²', '115m²', '158m²', '642m²', '1840m²', '430m²', '469m²',
       '1480m²', '666m²', '334m²', '333m²', '723m²', '485m²', '168m²',
       '143m²', '248m²', '2460m²', '128m²', '876m²', '427m²', '198m²',
       '809m²', '596m²', '533m²', '1031m²', '1860m²', '501m²', '633m²',
       '2653m²', '2384m²', '53m²', '784m²', '556m²', '1334m²', '242m²',
       '414m²', '995m²', '494m²', '2472m²', '265m²', '171m²', '2680m²',
       '306m²', '440m²', '535m²', '753m²', '1110m²', '137m²', '222m²',
       '508m²', '1772m²', '48494m²', '1335m²', '107m²', '241m²', '826m²',
       '321m²', '1427m²', '614m²', '933m²', '261m²', '451m²', '354m²',
       '345m²', '201m²', '336m²', '308m²', '280350m²', '755m²', '1215m²',
       '927m²', '1757m²', '490m²', '823m²', '2350m²', '1580m²', '780m²',
       '311m²', '4', '647m²', '537m²', '294m²', '357m²', '215m²',
       '1760m²', '479m²', '279m²', '174m²', '3400m²', '990m²', '1268m²',
       '146m²', '778m²', '89m²', '834m²', '1233m²', '269m²', '1486m²',
       '2250m²', '1250m²', '209m²', '449m²', '385m²', '3500m²', '652m²',
       '464m²', '956m²', '433m²', '926m²', '978m²', '399m²', '678m²',
       '637m²', '553m²', '419m²', '577m²', '274m²', '211m²', '436m²',
       '74m²', '475m²', '970m²', '2015m²', '443m²', '707m²', '7m²',
       '730m²', '765m²', '282m²', '807m²', '682m²', '349m²', '5', '386m²',
       '371m²', '40m²', '21180m²', '654m²', '289m²', '2056m²', '353m²',
       '71m²', '417m²', '1556m²', '411m²', '808m²', '1327m²', '329m²',
       '271m²', '298m²', '1547m²', '690m²', '961m²', '2240m²', '1168m²',
       '1560m²', '482m²', '1315m²', '301m²', '697m²', '223m²', '157m²',
       '742m²', '504m²', '193m²', '455m²', '1386m²', '739m²', '446m²',
       '310m²', '1780m²', '1040m²', '3', '492m²', '617m²', '178m²',
       '327m²', '2800m²', '1044m²', '326m²', '1167m²', '945m²', '88m²',
       '1025m²', '1199m²', '1750m²', '526m²', '1191m²', '1197m²', '199m²',
       '531m²', '421m²', '629m²', '51m²', '1260m²', '318m²', '1008m²',
       '6622m²', '272m²', '323m²', '9002m²', '566m²', '119m²', '179m²',
       '1740m²', '1325m²', '0', '597m²', '296m²', '544m²', '2359m²',
       '951m²', '879m²', '341m²', '1306m²', '1180m²', '1247m²', '483m²',
       '459m²', '2300m²', '363m²', '2317m²', '452m²', '634m²', '302m²',
       '888m²', '2957m²', '674m²', '75m²', '677m²', '1080m²', '228m²',
       '1021m²', '676m²', '562m²', '874m²', '588m²', '582m²', '431m²',
       '4600m²', '1140m²', '1360m²', '376m²', '734m²', '283m²', '402m²',
       '641m²', '1467m²', '618m²', '403m²', '134458m²', '277m²', '1045m²',
       '725m²', '564m²', '3000m²', '1326m²', '635m²', '911m²', '578m²',
       '735m²', '1006m²', '458m²', '1204m²', '50m²', '518m²', '368m²',
       '871m²', '736m²', '624m²', '907m²', '70m²', '611m²', '585m²',
       '920m²', '1755m²', '646m²', '1225m²', '748m²', '1020m²', '1125m²',
       '438m²', '558m²', '886m²', '934m²', '864m²', '899m²', '2027m²',
       '2', '816m²', '586m²', '2242m²', '766m²', '348m²', '847m²',
       '409m²', '700000m²', '602m²', '3680m²', '840m²', '878m²', '1474m²',
       '1650m²', '1440m²', '1188m²', '856m²', '898m²', '579m²', '118m²',
       '116m²', '293m²', '592m²', '745m²', '1220m²', '516m²', '623m²',
       '1797m²', '55m²', '610m²', '997m²', '1187m²', '2233m²', '548m²',
       '1602m²', '672m²', '1798m²', '2070m²', '5239m²', '2697m²', '236m²',
       '73m²', '892m²', '462m²', '679m²', '1004m²', '4500m²', '468m²',
       '437m²', '1821m²', '69m²', '1155m²', '299m²'], dtype=object)

In [40]:
new_df = new_df.loc[(new_df['metroscuadradostotales'] != 'metroscuadradostotales') & (new_df['precio'] != 'Consultar precio')].reset_index(drop=True)

In [41]:
new_df

,latlong,metroscuadradostotales,precio,titulo
0,//maps.google.com/maps/api/staticmap?center=-2...,480m²,USD 565.000,Arrecife - Punta Mocoli Design By Jannina Cabal
1,//maps.google.com/maps/api/staticmap?center=-2...,400m²,USD 370.000,Vendo Casa Moderna de Estreno en Isla Mocoli
2,//maps.google.com/maps/api/staticmap?center=-2...,244m²,USD 140.000,Venta de Casa Cdla. del Biess Remodelada - Sec...
3,//maps.google.com/maps/api/staticmap?center=-2...,1m²,USD 259.000,Se Vende Proyecto en Isla Celeste Reserva Solo...
4,//maps.google.com/maps/api/staticmap?center=-2...,245m²,USD 245.000,Isla Celeste 243 m² Const y 225 m² Terreno Her...
...,...,...,...,...
5012,//maps.google.com/maps/api/staticmap?center=nu...,660m²,USD 590.000,Proyecto Al Lago en La Peninsula - Mocoli
5013,//maps.google.com/maps/api/staticmap?center=nu...,700m²,USD 790.000,Venta Villa Preciosa Super Amplia 5 Dorm.
5014,//maps.google.com/maps/api/staticmap?center=-2...,350m²,USD 380.000,Oportunidad Moderna Casa en Via a La Costa Urb...
5015,//maps.google.com/maps/api/staticmap?center=nu...,256m²,USD 220.000,Venta C Celeste Villa 1 Sola Planta 1 Dormitor...
5016,//maps.google.com/maps/api/staticmap?center=nu...,230m²,USD 285.000,Villa X Uess 4 Dormitorio Estudio

In [42]:
new_df['titulo'].astype('float')

ValueError: could not convert string to float: 'Arrecife - Punta Mocoli Design By Jannina Cabal'

In [43]:
new_df['metroscuadradostotales'] = new_df['metroscuadradostotales'].str.replace('m²', '')

In [44]:
new_df['metroscuadradostotales'] = new_df['metroscuadradostotales'].astype('int64')

In [45]:
new_df['metroscuadradostotales']

0       480
1       400
2       244
3         1
4       245
       ...
5012    660
5013    700
5014    350
5015    256
5016    230
Name: metroscuadradostotales, Length: 5017, dtype: int64

In [46]:
new_df['precio'] = new_df['precio'].str.replace('USD', '').str.replace('.', '',regex=False).astype('int64')

In [47]:
new_df

,latlong,metroscuadradostotales,precio,titulo
0,//maps.google.com/maps/api/staticmap?center=-2...,480,565000,Arrecife - Punta Mocoli Design By Jannina Cabal
1,//maps.google.com/maps/api/staticmap?center=-2...,400,370000,Vendo Casa Moderna de Estreno en Isla Mocoli
2,//maps.google.com/maps/api/staticmap?center=-2...,244,140000,Venta de Casa Cdla. del Biess Remodelada - Sec...
3,//maps.google.com/maps/api/staticmap?center=-2...,1,259000,Se Vende Proyecto en Isla Celeste Reserva Solo...
4,//maps.google.com/maps/api/staticmap?center=-2...,245,245000,Isla Celeste 243 m² Const y 225 m² Terreno Her...
...,...,...,...,...
5012,//maps.google.com/maps/api/staticmap?center=nu...,660,590000,Proyecto Al Lago en La Peninsula - Mocoli
5013,//maps.google.com/maps/api/staticmap?center=nu...,700,790000,Venta Villa Preciosa Super Amplia 5 Dorm.
5014,//maps.google.com/maps/api/staticmap?center=-2...,350,380000,Oportunidad Moderna Casa en Via a La Costa Urb...
5015,//maps.google.com/maps/api/staticmap?center=nu...,256,220000,Venta C Celeste Villa 1 Sola Planta 1 Dormitor...
5016,//maps.google.com/maps/api/staticmap?center=nu...,230,285000,Villa X Uess 4 Dormitorio Estudio

In [48]:
new_df.iloc[5010,0]

'//maps.google.com/maps/api/staticmap?center=-2.1561673,-79.90530819999998&zoom=16&channel=PV&size=780x456&sensor=true&scale=2&key=AIzaSyBZ0l4aIUv2yia6kSFP_hc3Q4Z_lQ0Nl5w&signature=Z2LzDhQQlhMkf3GFEV3OTVJyDAU='

In [49]:
new_df[['lat', 'long']] = new_df['latlong'].str.split('=', expand=True)[1].str.split(',', expand=True)

In [50]:
new_df

,latlong,metroscuadradostotales,precio,titulo,lat,long
0,//maps.google.com/maps/api/staticmap?center=-2...,480,565000,Arrecife - Punta Mocoli Design By Jannina Cabal,-2.115345389952465,-79.85616255437014&zoom
1,//maps.google.com/maps/api/staticmap?center=-2...,400,370000,Vendo Casa Moderna de Estreno en Isla Mocoli,-2.102442901125957,-79.8670732875496&zoom
2,//maps.google.com/maps/api/staticmap?center=-2...,244,140000,Venta de Casa Cdla. del Biess Remodelada - Sec...,-2.230328339537673,-79.90216345507815&zoom
3,//maps.google.com/maps/api/staticmap?center=-2...,1,259000,Se Vende Proyecto en Isla Celeste Reserva Solo...,-2.071613787296468,-79.84206462327882&zoom
4,//maps.google.com/maps/api/staticmap?center=-2...,245,245000,Isla Celeste 243 m² Const y 225 m² Terreno Her...,-2.07941565850068,-79.83799314794919&zoom
...,...,...,...,...,...,...
5012,//maps.google.com/maps/api/staticmap?center=nu...,660,590000,Proyecto Al Lago en La Peninsula - Mocoli,null,null&zoom
5013,//maps.google.com/maps/api/staticmap?center=nu...,700,790000,Venta Villa Preciosa Super Amplia 5 Dorm.,null,null&zoom
5014,//maps.google.com/maps/api/staticmap?center=-2...,350,380000,Oportunidad Moderna Casa en Via a La Costa Urb...,-2.19522897016541,-80.05308412611731&zoom
5015,//maps.google.com/maps/api/staticmap?center=nu...,256,220000,Venta C Celeste Villa 1 Sola Planta 1 Dormitor...,null,null&zoom
5016,//maps.google.com/maps/api/staticmap?center=nu...,230,285000,Villa X Uess 4 Dormitorio Estudio,null,null&zoom

In [51]:
new_df['long'] = new_df['long'].str.replace('&zoom', '')

In [52]:
new_df.columns

Index(['latlong', 'metroscuadradostotales', 'precio', 'titulo', 'lat', 'long'], dtype='object')

In [53]:
new_df.columns = ['locacion', 'metroscuadradostotales', 'precio', 'titulo', 'latitud', 'longitud']

In [54]:
new_df = new_df.loc[(new_df['latitud'] != 'null') & (new_df['longitud'] != 'null')].reset_index(drop=True)

In [55]:
new_df

,locacion,metroscuadradostotales,precio,titulo,latitud,longitud
0,//maps.google.com/maps/api/staticmap?center=-2...,480,565000,Arrecife - Punta Mocoli Design By Jannina Cabal,-2.115345389952465,-79.85616255437014
1,//maps.google.com/maps/api/staticmap?center=-2...,400,370000,Vendo Casa Moderna de Estreno en Isla Mocoli,-2.102442901125957,-79.8670732875496
2,//maps.google.com/maps/api/staticmap?center=-2...,244,140000,Venta de Casa Cdla. del Biess Remodelada - Sec...,-2.230328339537673,-79.90216345507815
3,//maps.google.com/maps/api/staticmap?center=-2...,1,259000,Se Vende Proyecto en Isla Celeste Reserva Solo...,-2.071613787296468,-79.84206462327882
4,//maps.google.com/maps/api/staticmap?center=-2...,245,245000,Isla Celeste 243 m² Const y 225 m² Terreno Her...,-2.07941565850068,-79.83799314794919
...,...,...,...,...,...,...
4079,//maps.google.com/maps/api/staticmap?center=-2...,400,480000,Casa de Venta en Samborondon,-2.271652498184291,-78.9993077470703
4080,//maps.google.com/maps/api/staticmap?center=-2...,250,270000,Vendo Linda Casa en Los Primeros Kms de Sambor...,-2.140582502247502,-79.86876096242673
4081,//maps.google.com/maps/api/staticmap?center=-2...,136,120000,"Venta Casa en Urb. Villa Club, etapa Jupiter, ...",-2.028782049495582,-79.89546548465574
4082,//maps.google.com/maps/api/staticmap?center=-2...,560,220000,Vendo Propiedad de Oportunidad en Urdesa Norte,-2.1561673,-79.90530819999998
4083,//maps.google.com/maps/api/staticmap?center=-2...,350,380000,Oportunidad Moderna Casa en Via a La Costa Urb...,-2.19522897016541,-80.05308412611731

In [56]:
new_df['latitud'] = new_df['latitud'].astype('float64')
new_df['longitud'] = new_df['longitud'].astype('float64')

In [57]:
new_df.dtypes

locacion                   object
metroscuadradostotales      int64
precio                      int64
titulo                     object
latitud                   float64
longitud                  float64
dtype: object

In [58]:
new_df['latitud'].str.contains('null') #Alternativa al != en la serie booleana

AttributeError: Can only use .str accessor with string values!

In [59]:
new_df.drop(columns=['locacion'], inplace=True)

In [60]:
new_df

,metroscuadradostotales,precio,titulo,latitud,longitud
0,480,565000,Arrecife - Punta Mocoli Design By Jannina Cabal,-2.115345,-79.856163
1,400,370000,Vendo Casa Moderna de Estreno en Isla Mocoli,-2.102443,-79.867073
2,244,140000,Venta de Casa Cdla. del Biess Remodelada - Sec...,-2.230328,-79.902163
3,1,259000,Se Vende Proyecto en Isla Celeste Reserva Solo...,-2.071614,-79.842065
4,245,245000,Isla Celeste 243 m² Const y 225 m² Terreno Her...,-2.079416,-79.837993
...,...,...,...,...,...
4079,400,480000,Casa de Venta en Samborondon,-2.271652,-78.999308
4080,250,270000,Vendo Linda Casa en Los Primeros Kms de Sambor...,-2.140583,-79.868761
4081,136,120000,"Venta Casa en Urb. Villa Club, etapa Jupiter, ...",-2.028782,-79.895465
4082,560,220000,Vendo Propiedad de Oportunidad en Urdesa Norte,-2.156167,-79.905308
4083,350,380000,Oportunidad Moderna Casa en Via a La Costa Urb...,-2.195229,-80.053084

In [61]:
new_df['preciomt2'] = new_df['precio'] / new_df['metroscuadradostotales']

In [62]:
new_df

,metroscuadradostotales,precio,titulo,latitud,longitud,preciomt2
0,480,565000,Arrecife - Punta Mocoli Design By Jannina Cabal,-2.115345,-79.856163,1177.083333
1,400,370000,Vendo Casa Moderna de Estreno en Isla Mocoli,-2.102443,-79.867073,925.000000
2,244,140000,Venta de Casa Cdla. del Biess Remodelada - Sec...,-2.230328,-79.902163,573.770492
3,1,259000,Se Vende Proyecto en Isla Celeste Reserva Solo...,-2.071614,-79.842065,259000.000000
4,245,245000,Isla Celeste 243 m² Const y 225 m² Terreno Her...,-2.079416,-79.837993,1000.000000
...,...,...,...,...,...,...
4079,400,480000,Casa de Venta en Samborondon,-2.271652,-78.999308,1200.000000
4080,250,270000,Vendo Linda Casa en Los Primeros Kms de Sambor...,-2.140583,-79.868761,1080.000000
4081,136,120000,"Venta Casa en Urb. Villa Club, etapa Jupiter, ...",-2.028782,-79.895465,882.352941
4082,560,220000,Vendo Propiedad de Oportunidad en Urdesa Norte,-2.156167,-79.905308,392.857143
4083,350,380000,Oportunidad Moderna Casa en Via a La Costa Urb...,-2.195229,-80.053084,1085.714286

In [63]:
new_df.dtypes

metroscuadradostotales      int64
precio                      int64
titulo                     object
latitud                   float64
longitud                  float64
preciomt2                 float64
dtype: object

Tarea: Nuevo data set donde debemos dejar las mismas columnas y los procesos de limpieza
head()
dtypes
shape

In [64]:
new_df.drop_duplicates(subset=['latitud', 'longitud', 'metroscuadradostotales', 'precio'], inplace=True)

In [90]:
new_df

,metroscuadradostotales,precio,titulo,latitud,longitud,preciomt2,categoria
0,480,565000,Arrecife - Punta Mocoli Design By Jannina Cabal,-2.115345,-79.856163,1177.083333,A
1,400,370000,Vendo Casa Moderna de Estreno en Isla Mocoli,-2.102443,-79.867073,925.000000,B
2,244,140000,Venta de Casa Cdla. del Biess Remodelada - Sec...,-2.230328,-79.902163,573.770492,B
3,1,259000,Se Vende Proyecto en Isla Celeste Reserva Solo...,-2.071614,-79.842065,259000.000000,A
4,245,245000,Isla Celeste 243 m² Const y 225 m² Terreno Her...,-2.079416,-79.837993,1000.000000,B
...,...,...,...,...,...,...,...
3855,400,480000,Casa de Venta en Samborondon,-2.271652,-78.999308,1200.000000,A
3856,250,270000,Vendo Linda Casa en Los Primeros Kms de Sambor...,-2.140583,-79.868761,1080.000000,A
3857,136,120000,"Venta Casa en Urb. Villa Club, etapa Jupiter, ...",-2.028782,-79.895465,882.352941,B
3858,560,220000,Vendo Propiedad de Oportunidad en Urdesa Norte,-2.156167,-79.905308,392.857143,C
3859,350,380000,Oportunidad Moderna Casa en Via a La Costa Urb...,-2.195229,-80.053084,1085.714286,A

In [66]:
new_df.reset_index(drop=True, inplace=True)

In [87]:
def categorize(row):
    if row['preciomt2'] > 1000:
        return 'A'
    elif row['preciomt2'] > 500:
        return 'B'
    else:
        return 'C'

In [88]:
new_df['categoria'] = new_df.apply(categorize, axis=1, result_type='expand')

In [91]:
new_df.to_csv('../Output/data_2019_clean.csv', index=False)