In [2]:
import pandas as pd
import numpy as np

In [17]:
df = pd.read_csv(
    '../Data/201703_EnemduBDD_15anios.csv',
    sep=';',
    decimal=',',
    keep_default_na=False,
    na_values= [' ']
    )

In [11]:
df

,area,ciudad,zona,sector,panelm,vivienda,hogar,p01,p02,p03,...,desem,desemab,desemoc,desem1,desem2,pein,menor10,menor15,pobla10,pobla15
0,1,10150,1,3,112,1,1,1,1,54,...,,,,,,,,,1,1
1,1,10150,1,3,112,1,1,2,2,53,...,,,,,,,,,1,1
2,1,10150,1,3,112,1,1,3,2,15,...,,,,,,1,,,1,1
3,1,10150,1,3,112,2,1,1,2,51,...,,,,,,,,,1,1
4,1,10150,1,3,112,2,1,2,1,47,...,,,,,,,,,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59237,2,900451,999,7,182,3,1,4,2,22,...,,,,,,,,,1,1
59238,2,900451,999,7,182,3,1,5,2,37,...,,,,,,,,,1,1
59239,2,900451,999,7,182,3,1,6,1,13,...,,,,,,,,1,1,
59240,2,900451,999,7,182,3,1,7,2,4,...,,,,,,,1,1,,
59241,2,900451,999,7,182,4,1,1,2,74,...,,,,,,,,,1,1

In [18]:
df.dtypes

area         int64
ciudad       int64
zona         int64
sector       int64
panelm       int64
            ...
pein       float64
menor10    float64
menor15    float64
pobla10    float64
pobla15    float64
Length: 185, dtype: object

In [19]:
df['ingpc']

0        494.000000
1        494.000000
2        494.000000
3        352.000000
4        352.000000
            ...
59237    368.142857
59238    368.142857
59239    368.142857
59240    368.142857
59241    300.000000
Name: ingpc, Length: 59242, dtype: float64

In [4]:
df_spp = pd.read_spss(
    '../Data/201703_EnemduBDD_15anios.sav'
)

In [5]:
df_spp

,area,ciudad,zona,sector,panelm,vivienda,hogar,p01,p02,p03,...,desem,desemab,desemoc,desem1,desem2,pein,menor10,menor15,pobla10,pobla15
0,Urbana,10150.0,001,003,Panel K2,Vivienda Uno,Hogar Uno,Persona 1,Hombre,54.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,PoblaciÃ³n mayor o igual a 10 aÃ±os,PoblaciÃ³n mayor o igual a 15 aÃ±os
1,Urbana,10150.0,001,003,Panel K2,Vivienda Uno,Hogar Uno,Persona 2,Mujer,53.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,PoblaciÃ³n mayor o igual a 10 aÃ±os,PoblaciÃ³n mayor o igual a 15 aÃ±os
2,Urbana,10150.0,001,003,Panel K2,Vivienda Uno,Hogar Uno,Persona 3,Mujer,15.0,...,NaN,NaN,NaN,NaN,NaN,PoblaciÃ³n EconÃ³micamente Inactiva,NaN,NaN,PoblaciÃ³n mayor o igual a 10 aÃ±os,PoblaciÃ³n mayor o igual a 15 aÃ±os
3,Urbana,10150.0,001,003,Panel K2,Vivienda Dos,Hogar Uno,Persona 1,Mujer,51.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,PoblaciÃ³n mayor o igual a 10 aÃ±os,PoblaciÃ³n mayor o igual a 15 aÃ±os
4,Urbana,10150.0,001,003,Panel K2,Vivienda Dos,Hogar Uno,Persona 2,Hombre,47.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,PoblaciÃ³n mayor o igual a 10 aÃ±os,PoblaciÃ³n mayor o igual a 15 aÃ±os
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59237,Rural,900451.0,999,007,Panel R2,Vivienda Tres,Hogar Uno,Persona 4,Mujer,22.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,PoblaciÃ³n mayor o igual a 10 aÃ±os,PoblaciÃ³n mayor o igual a 15 aÃ±os
59238,Rural,900451.0,999,007,Panel R2,Vivienda Tres,Hogar Uno,Persona 5,Mujer,37.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,PoblaciÃ³n mayor o igual a 10 aÃ±os,PoblaciÃ³n mayor o igual a 15 aÃ±os
59239,Rural,900451.0,999,007,Panel R2,Vivienda Tres,Hogar Uno,Persona 6,Hombre,13.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,PoblaciÃ³n menor a 15 aÃ±os,PoblaciÃ³n mayor o igual a 10 aÃ±os,NaN
59240,Rural,900451.0,999,007,Panel R2,Vivienda Tres,Hogar Uno,Persona 7,Mujer,4.0,...,NaN,NaN,NaN,NaN,NaN,NaN,PoblaciÃ³n menor a 10 aÃ±os,PoblaciÃ³n menor a 15 aÃ±os,NaN,NaN
59241,Rural,900451.0,999,007,Panel R2,Vivienda Cuatro (reemplazo),Hogar Uno,Persona 1,Mujer,74.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,PoblaciÃ³n mayor o igual a 10 aÃ±os,PoblaciÃ³n mayor o igual a 15 aÃ±os

In [6]:
df_spp.dtypes

area       category
ciudad      float64
zona         object
sector       object
panelm     category
             ...
pein       category
menor10    category
menor15    category
pobla10    category
pobla15    category
Length: 185, dtype: object

In [7]:
df_spp['ingpc']

0        494.000000
1        494.000000
2        494.000000
3        352.000000
4        352.000000
            ...
59237    368.142857
59238    368.142857
59239    368.142857
59240    368.142857
59241    300.000000
Name: ingpc, Length: 59242, dtype: float64

In [8]:
df_spp.shape

(59242, 185)