In [88]:
import numpy as np
import pandas as pd

In [89]:
df = pd.read_csv(
    './Data/train.csv'
)

In [90]:
df.columns

Index(['Nose_x', 'Nose_y', 'Neck_x', 'Neck_y', 'RShoulder_x', 'RShoulder_y',
       'RElbow_x', 'RElbow_y', 'RWrist_x', 'RWrist_y', 'LShoulder_x',
       'LShoulder_y', 'LElbow_x', 'LElbow_y', 'LWrist_x', 'LWrist_y', 'RHip_x',
       'RHip_y', 'RKnee_x', 'RKnee_y', 'RAnkle_x', 'RAnkle_y', 'LHip_x',
       'LHip_y', 'LKnee_x', 'LKnee_y', 'LAnkle_x', 'LAnkle_y', 'REye_x',
       'REye_y', 'LEye_x', 'LEye_y', 'REar_x', 'REar_y', 'LEar_x', 'LEar_y',
       'postura', 'tipo_postura', 'postura_b'],
      dtype='object')

In [91]:
df = df.loc[:, ['RShoulder_x', 'RShoulder_y',
       'RElbow_x', 'RElbow_y', 'RWrist_x', 'RWrist_y', 'LShoulder_x',
       'LShoulder_y', 'LElbow_x', 'LElbow_y', 'LWrist_x', 'LWrist_y', 'RHip_x',
       'RHip_y', 'RKnee_x', 'RKnee_y', 'RAnkle_x', 'RAnkle_y', 'LHip_x',
       'LHip_y', 'LKnee_x', 'LKnee_y', 'LAnkle_x', 'LAnkle_y', 'REye_x',
       'REye_y', 'LEye_x', 'LEye_y', 'REar_x', 'REar_y', 'LEar_x', 'LEar_y',
       'postura']]

In [92]:
#df.dropna(inplace=True)

In [93]:
df

,RShoulder_x,RShoulder_y,RElbow_x,RElbow_y,RWrist_x,RWrist_y,LShoulder_x,LShoulder_y,LElbow_x,LElbow_y,...,LAnkle_y,REye_x,REye_y,LEye_x,LEye_y,REar_x,REar_y,LEar_x,LEar_y,postura
0,406.020,405.826,366.618,521.005,460.836,536.672,437.304,411.178,429.512,523.610,...,955.232,463.389,327.553,473.930,330.086,426.794,337.924,0.000,0.000,2
1,301.374,406.012,277.704,515.764,303.899,615.068,406.014,416.368,408.636,531.328,...,955.247,364.000,316.933,387.568,319.640,340.436,322.290,398.111,327.474,0
2,845.376,424.260,824.263,531.385,860.992,628.257,957.795,437.261,970.903,547.110,...,955.233,902.872,340.503,928.867,343.037,884.461,345.893,936.833,348.436,5
3,348.468,405.792,340.549,520.958,392.831,617.807,463.433,416.358,473.947,520.954,...,955.214,421.543,306.596,437.349,306.599,387.636,324.802,0.000,0.000,3
4,887.191,594.178,866.268,680.602,803.504,680.639,1015.390,594.277,1041.520,680.565,...,0.000,929.086,505.241,955.146,500.093,910.778,510.564,976.131,510.383,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32296,351.029,405.964,306.583,510.551,371.866,531.415,429.536,426.772,405.787,515.753,...,955.223,432.173,327.487,447.589,327.533,398.074,337.842,0.000,0.000,2
32297,285.677,405.896,262.164,518.380,303.829,635.974,374.487,424.246,382.340,526.227,...,955.219,353.606,322.151,371.930,322.199,322.330,330.110,0.000,0.000,0
32298,345.711,411.096,319.522,534.069,408.503,541.904,387.650,413.792,384.951,513.130,...,955.243,418.970,327.464,0.000,0.000,392.851,332.628,0.000,0.000,5
32299,680.666,418.980,659.646,539.306,680.638,656.972,777.359,429.580,785.241,552.469,...,955.248,764.201,343.069,782.577,343.210,727.673,343.110,0.000,0.000,3
32300,722.446,411.100,0.000,0.000,0.000,0.000,743.433,437.283,779.861,547.106,...,955.219,657.115,408.512,670.038,405.897,0.000,0.000,698.853,382.276,4

In [94]:
df['postura'].unique()

array([2, 0, 5, 3, 1, 4, 6])

In [95]:
df['postura'] = df['postura'].fillna(0)

In [96]:
df[df['postura'] == 0].shape

(4760, 33)

In [97]:
df[df['postura'] == 1].shape

(3613, 33)

In [98]:
df[df['postura'] == 2].shape

(6565, 33)

In [99]:
df[df['postura'] == 3].shape

(4056, 33)

In [100]:
df[df['postura'] == 4].shape

(3391, 33)

In [101]:
df[df['postura'] == 5].shape

(5820, 33)

In [102]:
df[df['postura'] == 6].shape

(4096, 33)

In [103]:
df_0 = df[df['postura'] == 0]
df_1 = df[df['postura'] == 1]
df_2 = df[df['postura'] == 2]
df_3 = df[df['postura'] == 3]
df_4 = df[df['postura'] == 4]
df_5 = df[df['postura'] == 5]
df_6 = df[df['postura'] == 6]

In [104]:
df_concat = pd.concat([df_0, df_1, df_2, df_3, df_4, df_5, df_6])

In [105]:
df_concat = df_concat.sample(frac=1).reset_index(drop=True)

In [106]:
# Downsamplo tipo_postura using the same number of samples for each class
df_down = df_concat.groupby('postura').apply(lambda x: x.sample(3391, replace=True, random_state=32)).reset_index(drop=True)

In [107]:
df_down

,RShoulder_x,RShoulder_y,RElbow_x,RElbow_y,RWrist_x,RWrist_y,LShoulder_x,LShoulder_y,LElbow_x,LElbow_y,...,LAnkle_y,REye_x,REye_y,LEye_x,LEye_y,REar_x,REar_y,LEar_x,LEar_y,postura
0,223.811,331.587,196.469,404.101,210.144,472.635,335.420,325.741,362.898,404.068,...,701.869,253.206,257.166,274.775,255.178,241.478,266.915,298.282,259.142,0
1,293.479,405.822,259.348,531.423,345.746,552.463,348.369,408.419,345.759,513.241,...,955.221,382.414,324.808,0.000,0.000,345.839,324.877,0.000,0.000,0
2,973.370,421.533,994.520,539.359,994.294,638.633,850.574,426.847,832.215,547.186,...,955.231,0.000,0.000,0.000,0.000,942.107,353.634,887.254,345.826,0
3,403.309,405.813,405.757,549.705,450.340,636.150,421.606,405.780,0.000,0.000,...,931.540,453.008,319.613,468.625,316.992,411.194,332.706,0.000,0.000,0
4,269.894,411.225,246.355,533.974,280.260,633.466,387.746,406.011,421.646,510.587,...,955.243,322.234,306.518,345.794,303.925,301.273,324.834,361.439,322.067,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23732,1036.890,337.529,989.875,394.274,917.319,384.445,1152.430,357.042,1183.830,435.464,...,715.643,1042.860,282.596,1058.500,280.623,0.000,0.000,1103.430,288.452,6
23733,324.802,408.592,301.238,534.010,384.860,531.352,419.002,408.623,426.839,523.641,...,955.230,411.135,319.590,0.000,0.000,369.388,324.915,0.000,0.000,6
23734,1079.990,347.251,1017.290,396.183,944.779,398.121,1207.310,368.823,1215.230,445.193,...,715.646,1132.900,274.697,1150.440,276.774,0.000,0.000,1181.810,298.261,6
23735,385.058,507.903,348.349,596.797,419.005,602.044,487.030,510.511,557.636,518.338,...,955.229,439.911,429.429,463.482,429.505,413.754,442.491,471.303,447.697,6
23736,387.546,387.555,387.490,547.160,432.104,683.191,413.732,382.288,0.000,0.000,...,0.000,434.758,285.662,450.323,288.229,395.493,301.228,0.000,0.000,6

In [108]:
df_down.to_csv('./Data/train_down.csv', index=False)